# Generated by Django 4.0.2 on 2022-03-10 09:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_client_time_zone_alter_message_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.PositiveIntegerField(validators=[django.core.validators.RegexValidator(message='номер телефона клиента в формате 7XXXXXXXXXX (X - цифра от 0 до 9)', regex='^7\\w{10}$')], verbose_name='Мобильный телефон'),
        ),
    ]
